apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  selector:
    app: website
  ports:
    - protocol: TCP
      name: http
      port: 80

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: website
  labels:
    app: website
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: docker.rikarin.org/cord/website
          imagePullPolicy: Always
